### ISSUE TITLE
off by one issue in continueParsing?

### ISSUE THREAD

**Issue by liamoc** [nineml/nineml#17]
Hi, thanks for the nice library. In 3.0.0f you added the helpful continueParsing method to a parsing result that allows me to swap in a new parser. But in my tests, it seems that it is parsing the last token of the first parse twice.

For example, assuming a simple arithmetic expression grammar, given the string `3 + 4   5`, I would expect the first parse to produce the tree of `3+4`, and then continueParsing to produce an expression consisting of just `5`. But in my results I get first the tree of `3 + 4`, then continueParsing gives me a tree with just `4`, and then continueParsing gives me `3 + 4` again.. I'm not sure if I'm misunderstanding something or if there is some issue with resuming parsing.

**Comment by ndw** [comment]
Interesting. I wrote a test case, but I suppose I could have got it wrong. Can you put together a small, reproducible example?

**Comment by liamoc** [comment]
Here is a MWE:
```java
import org.nineml.coffeegrinder.parser.SourceGrammar;
import org.nineml.coffeegrinder.parser.TerminalSymbol;
import org.nineml.coffeegrinder.tokens.TokenString;
import org.nineml.coffeegrinder.trees.StdoutTreeBuilder;

import java.util.Arrays;

public class MWE {

    public static void main(String[] args) {
        SourceGrammar g = new SourceGrammar();
        var expr = g.getNonterminal("expression");
        var number = g.getNonterminal("number");
        var plusToken = TokenString.get("+");
        var fiveToken = TokenString.get("5");
        var ftToken = TokenString.get("42");
        var plus = new TerminalSymbol(plusToken);
        g.addRule(expr,number,plus,expr);
        g.addRule(expr,number);
        g.addRule(number,new TerminalSymbol(fiveToken));
        g.addRule(number,new TerminalSymbol(ftToken));
        g.getParserOptions().setPrefixParsing(true);
        var parser = g.getParser(g.getParserOptions(),"expression");
        TokenString[] args2 = Arrays.stream(args).map(TokenString::get).toArray(TokenString[]::new);
        var result = parser.parse(args2);
        result.getArborist().getTree(new StdoutTreeBuilder());
        result = result.continueParsing();
        result.getArborist().getTree(new StdoutTreeBuilder());
    }
}
```
It parses the command line arguments, so each arg is a token. It only supports plus and the numbers 5 and 42, but demonstrates the same issue as my larger project:

Running this:
```bash
$ java -cp ".:coffeegrinder-3.2.0.jar" MWE 5 + 42 5 + 5
```
I get:
```
<expression><number>5</number>+<expression><number>42</number></expression></expression>
<expression><number>42</number></expression>
```

**Comment by ndw** [comment]
Thank you. At a quick glance, the first parse doesn't seem to be in a recoverable state after parsing the 42. I find that a little surprising. I will investigate as soon as I can.

**Comment by liamoc** [comment]
Thanks! And thanks for the library!
